### ISSUE TITLE
Graph Generation

### ISSUE THREAD

**Issue by hiratam1998** [PietroMSB/MG2N2#2]
I executed following code.
```
python translate_dataset.py
python train_generator.py Temp/Modules full
python train_bond_classifier.py Temp/Modules full
python train_linker.py Temp/Modules full
```
I think that MG2N2 is ready for graph generation at this time.
```
python generate_graph.py Temp/Modules
```
I have a question. Do I need to edit python file ?
Using package version is same in requirements version.

The image is a part of error message.
<img width="1434" alt="スクリーンショット 2021-11-18 16 57 22" src="https://user-images.githubusercontent.com/80070237/142375035-0df1cd46-6aa1-4a37-bc0a-541b019106ad.png">

**Comment by PietroMSB** [comment]
Hello,

Thank you for the question.
I believe this happens because the modules saved after training have different parameters from those re-declared in "generate_graphs.py". I am sorry, as this is a bit counter-intuitive, but given Tensorflow v1's way of saving and loading a neural network, it was my best effort at this.
In practice, at the beginning of "generate_graphs.py" you should declare the parameters of each of the networks you previously trained. The section you should edit is the following:
![image](https://user-images.githubusercontent.com/49313729/142387387-f8102d2f-5fdb-481b-b0f6-f79a49185e4c.png)

Let me know if everything works fine :)
Best,
Pietro

**Comment by hiratam1998** [comment]
worked ! 
I still need  to study python more.
Thanks, Dr.

**Comment by PietroMSB** [comment]
Nice to hear it works fine!
Good luck with your studies :)

**Comment by yash2002vardhan** [comment]
What exact edits do I have to make in the "generate_graphs.py" file ?
